#!/usr/bin/env python3.10

import sys
import threading
from socket import *
import time

def writeLog(fileName, timestamp, duration, serverIp, chunkName, chunkSize):
    with threading.Lock():
        with open(fileName, 'a') as f:
            f.write(f"{timestamp} {duration:.6f} {serverIp} {chunkName} {chunkSize}")
            f.flush()

# referenced https://realpython.com/intro-to-python-threading/
def newClientThread(clientSocket):
    print(f"Thread starting")
    time.sleep(2)
    print(f"Thread finished")

def main():
    logFilename = sys.argv[1]
    listenPort = int(sys.argv[2])
    fakeIp = sys.argv[3]
    serverIp = sys.argv[4]

    # Server socket for connections with the client    
    serverSocket = socket(AF_INET, SOCK_STREAM)
    serverSocket.bind(('', listenPort))
    serverSocket.listen(100)

    while True:
        clientSocket, addr = serverSocket.accept()
        clientThread = threading.Thread(
            target=newClientThread,
            args=(clientSocket,),
            daemon=True
        )
        clientThread.start()

    serverSocket.close()


if __name__ == "__main__":
    main()
